name = "lean-doodles"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanDoodles"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanDoodles"
